Repository QuantEcon/sphinxcontrib-jupyter, pull requests merged in 2018-11, with the labels that each got.

#112 FEAT: Add slideshow option into the metadata
  .gitignore
  docs/usage_jupyter_directive.rst
  sphinxcontrib/jupyter/__init__.py
  sphinxcontrib/jupyter/directive/jupyter.py
  sphinxcontrib/jupyter/writers/translate_all.py
  sphinxcontrib/jupyter/writers/translate_code.py
  tests/_static/.ignore
  tests/img/pimc.jpg
  tests/img/randbitmap_computer.png
  tests/img/randbitmap_true.png
  tests/index.rst
  tests/ipynb/_static/fill_demo1.png
  tests/ipynb/_static/simple_notebook.png
  tests/ipynb/_static/test_pwt.csv
  tests/ipynb/code_synonyms.ipynb
  tests/ipynb/collapse.ipynb
  tests/ipynb/download.ipynb
  tests/ipynb/equation_labels.ipynb
  tests/ipynb/ignore.ipynb
  tests/ipynb/images.ipynb
  tests/ipynb/index.ipynb
  tests/ipynb/inline.ipynb
  tests/ipynb/jupyter.ipynb
  tests/ipynb/links.ipynb
  tests/ipynb/links_target.ipynb
  tests/ipynb/lists.ipynb
  tests/ipynb/literal_include.ipynb
  tests/ipynb/notes.ipynb
  tests/ipynb/only.ipynb
  tests/ipynb/quote.ipynb
  tests/ipynb/simple_notebook.ipynb
  tests/ipynb/slides.ipynb
  tests/ipynb/solutions.ipynb
  tests/ipynb/tables.ipynb
  tests/ipynb/tests.ipynb
  tests/jupyter.rst
  tests/slides.rst
Labels: ready

#147 FEAT: add jupyter_target_html_urlprefix option
  sphinxcontrib/jupyter/__init__.py
  sphinxcontrib/jupyter/writers/translate_all.py
  sphinxcontrib/jupyter/writers/translate_code.py
Labels: WIP

#154 ENH: Update displaymath to use Latex tags rather than html table wrappers
  sphinxcontrib/jupyter/writers/translate_all.py
  tests/ipynb/equation_labels.ipynb
  tests/ipynb/footnotes.ipynb
  tests/ipynb/lists.ipynb
  tests/ipynb/math.ipynb
Labels: bug, high-priority
